// Generated by CoffeeScript 1.11.1
var NoExtraNewlines;

module.exports = NoExtraNewlines = (function() {
  function NoExtraNewlines() {}

  NoExtraNewlines.prototype.rule = {
    name: 'no_extra_newlines',
    level: 'ignore',
    message: "Extra newlines",
    description: 'This rule checks for unnecessary extra newlines between lines of code.'
  };

  NoExtraNewlines.prototype.max_empty = 1;

  NoExtraNewlines.prototype.n_empty = 0;

  NoExtraNewlines.prototype.lintLine = function(line, lineApi) {
    if (line.match(/^\s*$/) && !lineApi.isLastLine()) {
      this.n_empty += 1;
    } else {
      this.n_empty = 0;
    }
    return this.n_empty > this.max_empty;
  };

  return NoExtraNewlines;

})();
